### ISSUE TITLE
error using your sample code

### ISSUE THREAD

**Issue by dotob** [swissmanu/primus-responder#8]
with the sample code from the readme i get this error:

```

basti@imac:~/Development/rose/test|⇒  node server.js

/Users/basti/Development/rose/test/node_modules/primus/index.js:785
    throw new PrimusError('Middleware should be a function that accepts at least 2 args');
    ^
PrimusError: Middleware should be a function that accepts at least 2 args
    at Primus.use (/Users/basti/Development/rose/test/node_modules/primus/index.js:785:11)
    at Object.<anonymous> (/Users/basti/Development/rose/test/server.js:7:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

```
basti@imac:~/Development/rose/test|⇒  npm ls
test@1.0.0 /Users/basti/Development/rose/test
├─┬ primus@6.0.1
│ ├─┬ access-control@1.0.0
│ │ ├── millisecond@0.1.2
│ │ └── vary@1.1.0
│ ├── asyncemit@3.0.1
│ ├─┬ create-server@1.0.1
│ │ └── connected@0.0.2
│ ├─┬ diagnostics@1.0.1
│ │ ├─┬ colorspace@1.0.1
│ │ │ ├─┬ color@0.8.0
│ │ │ │ ├── color-convert@0.5.3
│ │ │ │ └─┬ color-string@0.3.0
│ │ │ │   └── color-name@1.1.1
│ │ │ └── text-hex@0.0.0
│ │ ├─┬ enabled@1.0.2
│ │ │ └── env-variable@0.0.3
│ │ └─┬ kuler@0.0.0
│ │   └── colornames@0.0.2
│ ├── eventemitter3@1.2.0
│ ├── forwarded-for@1.0.1
│ ├─┬ fusing@1.0.0
│ │ ├── emits@3.0.0
│ │ └─┬ predefine@0.1.2
│ │   └── extendible@0.1.1
│ ├─┬ setheader@0.0.4
│ │ └── debug@0.7.4
│ ├── ultron@1.0.2
│ └── yeast@0.1.2
�┬ primus-responder@1.0.4
│ ├── debug@0.8.1
│ └── node-uuid@1.4.7
└─┬ ws@1.1.1
  └── options@0.0.6
```

any ideas?

sebastian

**Comment by dotob** [comment]
downgraded to primus 5.2.2, the error is not there. seems a breaking change in primus?

**Comment by dotob** [comment]
yes it is: https://github.com/primus/primus/releases/tag/6.0.0
when i changes the code to primus.plugin('responder', PrimusResponder); the serverside worked.

**Comment by dotob** [comment]
when i try to use primus-responder ín a node client like this:

```javascript
var Primus = require('primus');
var Socket = Primus.createSocket()
   , client = new Socket('http://localhost:8080');
// Handle incoming requests:
client.on('request', function(data, done) {
    // Echo the received request data
    done(data);
});

// Request a response from the server:
client.writeAndWait('request from client', function(response) {
    // Write the servers response to console
    console.log('Response from server:', response);
});
```

i get : 

```
basti@imac:~/Development/rose/test|⇒  node client.js
/Users/basti/Development/rose/test/client.js:11
client.writeAndWait('request from client', function(response) {
       ^

TypeError: client.writeAndWait is not a function
    at Object.<anonymous> (/Users/basti/Development/rose/test/client.js:11:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

ideas?

**Comment by swissmanu** [comment]
hi sebastian

thank you for your investigation and report so far.
i do not have the time to look after `primus-responder` more in-depth currently, sorry.

i heard once that the current version might not be compatible with the latest version of `primus`. making it work with `primus` > 6 would be a very welcome contribution to the project if you like to make the effort.

thanks you,
manuel

**Comment by helderbrandao** [comment]
Works for me! Set callbacks options with primus-responder object

``` javascript
var Primus = require('primus')
, PrimusCallbacks = require('primus-responder');

var options = {
    "plugin": {
        "callbacks": PrimusCallbacks
    }
};

var Socket = Primus.createSocket(options)
   , client = new Socket('http://localhost:8080');
// Handle incoming requests:
client.on('request', function(data, done) {
    // Echo the received request data
    done(data);
});

// Request a response from the server:
client.writeAndWait('request from client', function(response) {
    // Write the servers response to console
    console.log('Response from server:', response);
});
```

**Comment by dotob** [comment]
hi @helderbrandao ,

do you think this would work from the server side? meaning: request something from the client? how would i configure this?

thanks alot

**Comment by helderbrandao** [comment]
Hi @dotob 
Yes it works perfectly! 

client.js

``` javascript
var Primus = require('primus')
, PrimusCallbacks = require('primus-responder');

var options = {
    "plugin": {
        "callbacks": PrimusCallbacks
    }
};

var Socket = Primus.createSocket(options)
   , client = new Socket('http://localhost:8989');
// Handle incoming requests:
client.on('request', function(data, done) {
    // Echo the received request data
    done(data);
});

// Request a response from the server:
client.writeAndWait('request from client', function(response) {
    // Write the servers response to console
    console.log('Response from server:', response);
});
```

server.js

``` javascript
var express = require('express');
var bodyParser = require('body-parser');
var cookieParser    = require('cookie-parser');
var Primus = require('primus');
var responder = require('primus-responder');
var http = require('http');

var app = express();
app.set('port', 8989);
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(cookieParser());

var server = http.createServer(app);
server.listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
    this.primus = new Primus(this, {use_clock_offset: true});
    this.primus.plugin('responder', responder);
    this.primus.server.on('listening', function () {
        console.ĺog('WebSocket Running ' + this.address());
    });
    this.primus.on('connection', function (spark) {
        spark.on('request', function (data, done) {
            console.log("data", data);
            done({"ola": 1234});
        });
        spark.on('data', function (data) {
            console.log("data", data);
        });
    });
    this.primus.on('disconnection', function (spark) {
        console.log("disconnection");
    });
    this.primus.on('destroy', function (spark) {
        console.log("destroy");
    });
});
```

**Comment by dotob** [comment]
hi @helderbrandao,

sorry took me a while to get here. works perfectly. thanks a lot for the sample. was easy to spot my error.
would be great if your sample get in the readme.

sebastian
